vich_uploader:
    db_driver: orm

    mappings:
        authors:
            uri_prefix: /images/auteurs
            upload_destination: '%kernel.project_dir%/public/images/auteurs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        books:
            uri_prefix: /images/livres
            upload_destination: '%kernel.project_dir%/public/images/livres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        categories:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        carousel:
            uri_prefix: /images/carousel
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

